### ISSUE TITLE
Only returns up to 6 cards, not 7 as stated

### ISSUE THREAD

**Issue by charlie-collard** [d-schmidt/hearthscan-bot#5]
https://www.reddit.com/r/hearthstone/comments/9wsaf2/blizzard_stop_the_cyber_bullying/e9n48mi/

**Comment by d-schmidt** [comment]
Okay, it didn't know the Gnome yet:
https://github.com/d-schmidt/hearthscan-bot/blame/311029c1b3ee51a5979387b82143fe7d3f40c28a/data/tempinfo.json#L347

It should have shown the Guardian at least.
