### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by masudr4n4** [d-schmidt/hearthscan-bot#7]
Hey!
I am a designer want to make a design for this projects if you have any requirments then let me know.i just need a permission to work on it.
thanks

**Comment by d-schmidt** [comment]
Sounds nice. Feel free to design something.

**Comment by masudr4n4** [comment]
@Tobaloidee can you help here by contributing actually i am in a problem so can not contribute right now.
good luck

**Comment by Tobaloidee** [comment]
Surely buddy..i hope you are fine. @d-schmidt is it okay with you? Thanks!

**Comment by Tobaloidee** [comment]
@d-schmidt i made 2 versions. Still open to your suggestions

V1
![HEARTHSCAN-BOT PRES-01](https://user-images.githubusercontent.com/36028424/55940571-f81a2180-5c72-11e9-8f0d-1c32fdd3b64a.png)

V2
![HEARTHSCAN-BOT PRES2-01-02](https://user-images.githubusercontent.com/36028424/55940584-00725c80-5c73-11e9-9d0f-5dc00752086c.png)

**Comment by d-schmidt** [comment]
@Tobaloidee these are nice, I'm not at home at the moment. I will come back to this offer in a few days

**Comment by Tobaloidee** [comment]
Okay Sir.will wait for that time 😃

**Comment by d-schmidt** [comment]
@Tobaloidee V2 looks more friendly. I think I would use this one

wow this is hard. V1 is clever. I like it.

**Comment by Tobaloidee** [comment]
I think version 2 fits better and more friendly! will finalize the files now and make a PR with it @d-schmidt 
👍

**Comment by Tobaloidee** [comment]
Hi, @d-schmidt  Here's the PR #9 with the logo upload & readme update! later on, I will share my drive link for the other file formats and versions for you to download.  Thanks a lot!

**Comment by d-schmidt** [comment]
@Tobaloidee cool! Will merge it probably tomorrow.

**Comment by Tobaloidee** [comment]
Hi @d-schmidt 
Here's the link to my drive where you can download the different versions & formats of the Logo
[DOWNLOAD](https://drive.google.com/drive/u/1/folders/1rT1nliUhwu0qSiLToHIuO1D0B_ERvga8)

Thanks!
