### ISSUE TITLE
Database question

### ISSUE THREAD

**Issue by Zylvian** [d-schmidt/hearthscan-bot#8]
Hi!

I love your bot and its concept, and I'm aiming to make something similar for r/OnePiece.

My initial idea - and what I thought you did - was parse names off of a page (which would be https://onepiece.fandom.com/wiki/One_Piece_Wiki in my case) but I see you have it stored in a JSON locally.

So:
1. Where do you get this JSON info from?
2. Do you need to manually update it?
3. Why not parse from a website instead?

Thanks a lot!

**Comment by d-schmidt** [comment]
Hi,

it would be slow to parse the website each time you find a name on reddit.
I'm parsing some websites and hearthstone-json.com and combine all the informations into one json file for easy access. See [scrape.py](/d-schmidt/hearthscan-bot/blob/master/scrape.py)
Changes in cards are rare (few times a year).
